pipeline: hifi-assembly-purge-dups
version: 1.0
parser:
  help: Purge duplicate haplotigs from HiFi assemblies
  arg-groups:
    basic:
      mutually-exclusive-args:
        input-parser:
          required: True
      args:
        hifi-fastq:
          help: "Wildcard statement to represent HiFi FASTQs"
          type: str
          required: True
          action: confirmFile
        hifi-copy-method:
          help: "Specifies if HiFi FASTQs should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        assembly-fasta:
          help: "Wildcard statement to represent assembly FASTAs"
          type: str
          action: confirmFile
          required: True
        assembly-copy-method:
          help: "Specifies if the assembly FASTA should be copied or symbolically linked."
          choices:
            - 'symbolic_link'
            - 'copy'
          default: 'symbolic_link'
        species:
          help: "Species name"
          type: str
          default:
            str: "Sp"
            suffix:
              - function: jobRandomString
        assembly-version:
          help: "Assembly Version"
          type: str
          default:
            str: "v"
            suffix:
              - function: jobRandomString

setup:
  hifi_input:
    methods: 
      file-str: "{hifi-fastq}"
    args:
      standardized_filename: "HiFi/FASTQ/{species}.fq.gz"
      copy_method: "{fastq-copy-method}"

  assembly_input:
    methods:
      file-str: "{assembly-fasta}"
    args:
      standardized_filename: "Assembly/hifiasm/{species}_{assembly-version}.fa"
      copy_method: "{assembly-copy-method}"
      gzipped: False

snakemake:
  modules:
    - hifi_reseq_purge_dups




